ministryofjustice/hmpps-prison-visits-testing-helper-api

.circleci/config.yml
Changes to allow for staging release.
=> VB-3311 Release staging server Circle CI change

.circleci/config.yml, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsprisonvisitstestinghelperapi/controller/TestingDApiBHelperController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsprisonvisitstestinghelperapi/dto/VisitStatus.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsprisonvisitstestinghelperapi/repository/VisitRepository.kt
Added new end point to allow tests to change status of bookings.
=> New end point to change visit status

helm_deploy/hmpps-prison-visits-testing-helper-api/values.yaml
added allowed circle CI ip group
=> VB-3311 added allowed circle CI ip group

build.gradle.kts, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsprisonvisitstestinghelperapi/controller/TestingDBApiBHelperController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsprisonvisitstestinghelperapi/repository/VisitRepository.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsprisonvisitstestinghelperapi/service/DBService.kt
Add new endpoint to delete visit notifications and update to latest spring boot version and remove unused dependencies.
=> Add new endpoint to delete visit notifications and update dependency versions.

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsprisonvisitstestinghelperapi/client/VisitSchedulerClient.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsprisonvisitstestinghelperapi/controller/TestingAdminApiHelperController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsprisonvisitstestinghelperapi/dto/PrisonExcludeDateDto.kt
create a Test controller for Admin API calls to add and remove exclude dates.
=> Vb 3544 create a Test controller for Admin API calls to add and remove exclude dates.

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsprisonvisitstestinghelperapi/controller/TestingDBApiBHelperController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsprisonvisitstestinghelperapi/repository/DBRepository.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsprisonvisitstestinghelperapi/service/DBService.kt
This can be used to move the date into the past, and will be used by our test team to write an automated test for the reserve functionality
=> Add an endpoint to update the modifyTime of an application

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsprisonvisitstestinghelperapi/controller/TestingDBApiBHelperController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsprisonvisitstestinghelperapi/repository/DBRepository.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsprisonvisitstestinghelperapi/service/DBService.kt
The query expected a timestamp but I was passing in a LocalDate. Do a conversion to fix that issue.
=> Fix localdate timestamp missmatch

renovate.json
As described. This will allow renovate to auto raise a PR for review when a dependency needs updating.
=> Change renovate config to allow it to raise a pr when it finds a change

README.md, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsprisonvisitstestinghelperapi/controller/TestingSQSApiHelperController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsprisonvisitstestinghelperapi/dto/DomainEvent.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsprisonvisitstestinghelperapi/dto/PrisonerAlertCreatedUpdatedEventDto.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsprisonvisitstestinghelperapi/service/EventHandlerService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsprisonvisitstestinghelperapi/service/SQSService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsprisonvisitstestinghelperapi/helper/JwtAuthHelper.kt
Introduce an API endpoint on the testing-helper-api to trigger an SQS event for the domain event prisoner-alert-updated
https://dsdmoj.atlassian.net/browse/VB-3763
=> Feature: VB-3763 - Prisoner alert change events are processed

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsprisonvisitstestinghelperapi/controller/TestingSQSApiHelperController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsprisonvisitstestinghelperapi/dto/PrisonerReceivedEventDto.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsprisonvisitstestinghelperapi/service/EventHandlerService.kt
* VB-2761 Prisoner transferred events are processed
=> VB-2761 Prisoner transferred events are processed (#47)

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsprisonvisitstestinghelperapi/controller/TestingDBApiBHelperController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsprisonvisitstestinghelperapi/repository/DBRepository.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsprisonvisitstestinghelperapi/service/DBService.kt
Add new endpoint to alter a visits prison, to help test transfer events correctly flag a visit from old prison.
=> Feature: VB-2761 - Prisoner transfer events are processed

.trivyignore, build.gradle.kts
Update to kotlin 2.0 and dps-gradle v6.0
=> Update to kotlin 2.0 and dps-gradle v6.0

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsprisonvisitstestinghelperapi/controller/TestingDBApiBHelperController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsprisonvisitstestinghelperapi/repository/DBRepository.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsprisonvisitstestinghelperapi/service/DBService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsprisonvisitstestinghelperapi/helper/ClientHelper.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsprisonvisitstestinghelperapi/integration/DBApiHelperControllerIntegrationTest.kt
A quick addition to testing api for @HShivashankarappa will add tests later
=> VB-4065 Create testing api end point to change capacity

helm_deploy/values-dev.yaml, helm_deploy/values-staging.yaml, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsprisonvisitstestinghelperapi/client/PrisonApiClient.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsprisonvisitstestinghelperapi/config/HmppsPrisonVisitsTestingHelperApiExceptionHandler.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsprisonvisitstestinghelperapi/config/WebClientConfiguration.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsprisonvisitstestinghelperapi/controller/PrisonerController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsprisonvisitstestinghelperapi/dto/prison/api/VisitBalancesDto.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsprisonvisitstestinghelperapi/exception/NotFoundException.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsprisonvisitstestinghelperapi/service/PrisonerService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsprisonvisitstestinghelperapi/service/VisitService.kt, src/main/resources/application-dev.yml, src/main/resources/application.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsprisonvisitstestinghelperapi/integration/IntegrationTestBase.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsprisonvisitstestinghelperapi/integration/PrisonerControllerIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsprisonvisitstestinghelperapi/integration/mock/PrisonApiMockServer.kt, src/test/resources/application-test.yml
Add new endpoint to allow automation tests to capture the current VO balance of a prisoner.
=> New: Prisoner Controller with endpoint to get available VO balance of given prisoner

helm_deploy/values-dev.yaml, helm_deploy/values-staging.yaml, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsprisonvisitstestinghelperapi/client/VisitSchedulerClient.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsprisonvisitstestinghelperapi/controller/VisitAdminController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsprisonvisitstestinghelperapi/repository/SessionTemplateRepository.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsprisonvisitstestinghelperapi/service/SessionService.kt
Update to original code to create session on the fly
=> Still having transaction issues

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsprisonvisitstestinghelperapi/client/VisitSchedulerClient.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsprisonvisitstestinghelperapi/controller/ApplicationController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsprisonvisitstestinghelperapi/controller/VisitController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsprisonvisitstestinghelperapi/dto/visit/scheduler/BookingRequestDto.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsprisonvisitstestinghelperapi/dto/visit/scheduler/CreateApplicationDto.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsprisonvisitstestinghelperapi/repository/ApplicationRepository.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsprisonvisitstestinghelperapi/repository/SessionSlotRepository.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsprisonvisitstestinghelperapi/service/ApplicationService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsprisonvisitstestinghelperapi/service/SessionSlotService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsprisonvisitstestinghelperapi/service/VisitService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsprisonvisitstestinghelperapi/util/ReferenceGenerator.kt
VB-4288 - create and book an application to replicate an existing booked visit.
=> VB-4288 - create and book an application 

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsprisonvisitstestinghelperapi/client/VisitSchedulerClient.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsprisonvisitstestinghelperapi/dto/PrisonExcludeDateDto.kt
Switched to the new endpoint to add and remove blocked. dates for a prison.
=> VB-4433 - Update endpoint APIs called on visit-scheduler for add and remove endpoints

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsprisonvisitstestinghelperapi/controller/VisitAdminController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsprisonvisitstestinghelperapi/dto/admin/CreateSessionTemplateRequestDto.kt
Initially required a lot of request params which was messy. Converted it to a DTO.
=> Convert request params to DTO and improve logging

helm_deploy/hmpps-prison-visits-testing-helper-api/values.yaml
Errors appeared after upgrading dps-spring-boot to 7.1.0. This is the fix
=> Fix application insights deserialisation errors

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsprisonvisitstestinghelperapi/client/BookerRegistryClient.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsprisonvisitstestinghelperapi/dto/booker/registry/SearchBookerDto.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsprisonvisitstestinghelperapi/dto/enums/ApplicationStatus.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsprisonvisitstestinghelperapi/dto/enums/VisitSubStatus.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsprisonvisitstestinghelperapi/repository/VisitRepository.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsprisonvisitstestinghelperapi/service/VisitService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsprisonvisitstestinghelperapi/integration/ApplicationControllerIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsprisonvisitstestinghelperapi/integration/IntegrationTestBase.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsprisonvisitstestinghelperapi/integration/VisitControllerIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsprisonvisitstestinghelperapi/integration/mock/BookerRegistryApiMockServer.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsprisonvisitstestinghelperapi/repository/TestDBRepository.kt
Update booker search by email address endpoint, delete visit call, create visit notification. Also add new substatus to Visit and status to Application and fixed failing tests.
=> Updates to cater to changes in booker-registry and visit-scheduler
